spring.application.name=firstSpring


spring.datasource.url=url=jdbc:postgresql://dpg-d7s4p7pj2pic73fnlebg-a:5432/tudentdb
#spring.datasource.url=jdbc:mysql://mysql:3306/studentdb
spring.datasource.username=tudentdb_user
spring.datasource.password=Fxijw9ipwW2jaRsXCwZl4PLMgBdZdpKw

## Kubernate
#spring.datasource.url=jdbc:mysql://localhost:3307/mydb
#spring.datasource.username=root
#spring.datasource.password=root



spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

management.endpoints.web.exposure.include=*
